### ISSUE TITLE
client.py exception

### ISSUE THREAD

**Issue by kaiwa** [bromix/plugin.video.rtl-now.de#8]
Glaube irgendwas haben die heute an der Seite geändert. Heute Morgen lief es noch. Log unten ist vom 2.1.1 branch.

```
18:57:45 T:139985050437568   DEBUG: StartScript - calling plugin RTL NOW('plugin://plugin.video.rtl-now.de/play/','4','?video_id=192255')
18:57:45 T:139985050437568   DEBUG: WaitOnScriptResult - waiting on the RTL NOW (id=4) plugin...
18:57:45 T:139983801648896  NOTICE: Thread LanguageInvoker start, auto delete: false
18:57:45 T:139983801648896    INFO: initializing python engine.
18:57:45 T:139983801648896   DEBUG: CPythonInvoker(4, /home/kai/.kodi/addons/plugin.video.rtl-now.de-2.1.1/default.py): start processing
18:57:45 T:139983801648896  NOTICE: -->Python Interpreter Initialized<--
18:57:45 T:139983801648896   DEBUG: CPythonInvoker(4, /home/kai/.kodi/addons/plugin.video.rtl-now.de-2.1.1/default.py): the source file to load is "/home/kai/.kodi/addons/plugin.video.rtl-now.de-2.1.1/default.py"
18:57:45 T:139983801648896   DEBUG: CPythonInvoker(4, /home/kai/.kodi/addons/plugin.video.rtl-now.de-2.1.1/default.py): setting the Python path to /home/kai/.kodi/addons/plugin.video.rtl-now.de-2.1.1:/usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gtk-2.0:/usr/lib/pymodules/python2.7:/usr/lib/python2.7/dist-packages/ubuntu-sso-client:/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode
18:57:45 T:139983801648896   DEBUG: CPythonInvoker(4, /home/kai/.kodi/addons/plugin.video.rtl-now.de-2.1.1/default.py): entering source directory /home/kai/.kodi/addons/plugin.video.rtl-now.de-2.1.1
18:57:45 T:139983801648896   DEBUG: CPythonInvoker(4, /home/kai/.kodi/addons/plugin.video.rtl-now.de-2.1.1/default.py): instantiating addon using automatically obtained id of "plugin.video.rtl-now.de" dependent on version 2.14.0 of the xbmc.python api
18:57:45 T:139985050437568   DEBUG: ------ Window Deinit (Pointer.xml) ------
18:57:45 T:139984203568896   DEBUG: Caching image 'http://autoimg.rtl.de/ntvnow/2243-default_image_169_format/768x432/8b6ba.jpg' to '0/01ca53e8.jpg':
18:57:45 T:139984203568896   DEBUG: cached image 'special://masterprofile/Thumbnails/0/01ca53e8.jpg' size 768x432
18:57:45 T:139983801648896   DEBUG: [plugin.video.rtl-now.de] Starting Kodion framework by bromix...
18:57:45 T:139983801648896  NOTICE: [plugin.video.rtl-now.de] Running: RTL NOW (2.1.1) on Helix (2.19) with Python 2.7.6
18:57:45 T:139983801648896   DEBUG: [plugin.video.rtl-now.de] Path: "/play/
18:57:45 T:139983801648896   DEBUG: [plugin.video.rtl-now.de] Params: "{'video_id': u'192255'}"
18:57:46 T:139984247691008   DEBUG: CCurlFile::GetMimeType - http://mirrors.kodi.tv/addons/gotham/plugin.video.snagfilms/icon.png -> image/png
18:57:46 T:139984247691008   DEBUG: CurlFile::Open(0x7f508803d790) http://mirrors.kodi.tv/addons/gotham/plugin.video.snagfilms/icon.png
18:57:46 T:139984247691008   DEBUG: CCurlFile::Open - effective URL: <http://mirror.de.leaseweb.net/xbmc/addons/gotham/plugin.video.snagfilms/icon.png>
18:57:46 T:139984247691008   DEBUG: Caching image 'http://mirrors.kodi.tv/addons/gotham/plugin.video.snagfilms/icon.png' to '2/2db8fb39.png':
18:57:46 T:139984247691008   DEBUG: cached image 'special://masterprofile/Thumbnails/2/2db8fb39.png' size 256x256
18:57:46 T:139983801648896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'replace'
                                            Traceback (most recent call last):
                                              File "/home/kai/.kodi/addons/plugin.video.rtl-now.de-2.1.1/default.py", line 5, in <module>
                                                runner.run(__provider__)
                                              File "/home/kai/.kodi/addons/plugin.video.rtl-now.de-2.1.1/resources/lib/kodion/runner.py", line 32, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/kai/.kodi/addons/plugin.video.rtl-now.de-2.1.1/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "/home/kai/.kodi/addons/plugin.video.rtl-now.de-2.1.1/resources/lib/kodion/abstract_provider.py", line 123, in navigate
                                                result = method(context, re_match)
                                              File "/home/kai/.kodi/addons/plugin.video.rtl-now.de-2.1.1/resources/lib/kodion/register_provider_path.py", line 12, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/kai/.kodi/addons/plugin.video.rtl-now.de-2.1.1/resources/lib/rtlinteractive/provider.py", line 134, in _on_play
                                                server_id = context.get_function_cache().get(FunctionCache.ONE_HOUR * 6, Client.get_server_id)
                                              File "/home/kai/.kodi/addons/plugin.video.rtl-now.de-2.1.1/resources/lib/kodion/utils/function_cache.py", line 104, in get
                                                cached_data = partial_func()
                                              File "/home/kai/.kodi/addons/plugin.video.rtl-now.de-2.1.1/resources/lib/rtlinteractive/client.py", line 149, in get_server_id
                                                streams = rtl_client.get_film_streams(film_id)
                                              File "/home/kai/.kodi/addons/plugin.video.rtl-now.de-2.1.1/resources/lib/rtlinteractive/client.py", line 217, in get_film_streams
                                                player_url = player_url.replace('.liveab.swf', '.swf')
                                            AttributeError: 'NoneType' object has no attribute 'replace'
                                            -->End of Python script error report<--
```

**Comment by bromix** [comment]
Jup, die haben einen Redirect über ein Script realisiert :) sehr nett aber einfach zu lösen ^^ Danke für den Hinweis

**Comment by kaiwa** [comment]
Funktioniert wieder, sehr geil, thx.

**Comment by RomanOnymous** [comment]
Danke für den fixen Fix!

**Comment by bromix** [comment]
;)
